---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPCId:
    Type: "String"
  Subnets:
    Type: "List<AWS::EC2::Subnet::Id>"
  CodeLocationKey:
    Type: "String"
  CodeLocationKey2:
    Type: "String"
Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "SG for lambda in VPC"
      GroupName: "UniqueGroupName"
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        CidrIp: "0.0.0.0/0"
        FromPort: 443
        ToPort: 443
      VpcId:
        Ref: "VPCId"
  Bucket:
    Type: "AWS::S3::Bucket"
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Principal:
            Service:
            - "lambda.amazonaws.com"
        Version: "2012-10-17"
      ManagedPolicyArns:
      - Fn::Join:
        - ""
        - - "arn:"
          - Ref: "AWS::Partition"
          - ":iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Path: "/anotherPath/"
      Policies:
      - PolicyDocument:
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogStream"
            Resource:
            - Fn::Join:
              - ""
              - - "arn:"
                - Ref: "AWS::Partition"
                - ":logs:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":log-group:/aws/lambda/myService-nonprod-definition:*"
          - Effect: "Allow"
            Action:
            - "logs:PutLogEvents"
            Resource:
            - Fn::Join:
              - ""
              - - "arn:"
                - Ref: "AWS::Partition"
                - ":logs:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":log-group:/aws/lambda/myService-nonprod-definition:*"
                - ":*"
          Version: "2012-10-17"
        PolicyName: "nonprod-myService-lambda"
      RoleName:
        Fn::Join:
        - ""
        - - "myService-nonprod-"
          - Ref: "AWS::Region"
          - "-lambdaRole"
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/lambda/myService-nonprod-myFunction"
  Function:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Ref: "Bucket"
        S3Key:
          Ref: "CodeLocationKey"
      Handler: "org.http4k.serverless.lambda.LambdaFunction::handle"
      Role:
        Ref: "Role"
      Runtime: "java8"
  LogGroup2:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/lambda/myService-nonprod-myFunction2"
  Function2:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Ref: "Bucket"
        S3Key:
          Ref: "CodeLocationKey2"
      Handler: "org.http4k.serverless.lambda.LambdaFunction::handle"
      Role:
        Ref: "Role"
      Runtime: "java8"
      Environment:
        Variables:
          HTTP4K_BOOTSTRAP_CLASS: "handler"
      Timeout: 20
      VpcConfig:
        SecurityGroupIds:
        - Ref: "SecurityGroup"
        SubnetIds:
          Ref: "Subnets"
  RestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "nonprod-myService"
